### PR TITLE
Refactor how the generator works wrt autogeneration

### PR DESCRIPTION
**Pull request by luxas**
Fixes https://github.com/cloud-native-nordics/meetups/issues/79
Fixes https://github.com/cloud-native-nordics/artwork/issues/12

This PR rewrites the format of meetup.yaml to **only contain human-generated data**.
The autogenerated data wrt meetups is now put in the `autogenerated/` folder.

This PR has some mechanical changes:
 - Moves around the vendor/go.mod/etc. folders, so Go understands what to do (this worked poorly before, due to the non-standard layout we had here)
 - Removes the unit tests, because it is really not compatible with the flow we now have. When we see where we arrive with this new flow, we can refactor, and write proper tests for this.

This PR has some new features as well:
 - Longitude/latitude is now stored
 - Ignoring meetups can now be done by date, not ID
 - Way easier getting started guide to follow :smile:

cc @kaspernissen @netumoliver @Solisol @AllanHoejgaardJensen

### CODE REVIEW

**Comment by luxas** [comment]
cc @jepp2078 this will affect the stats-api, with this slightly updated config.json structure.

**Comment by Steiniche** [comment]
🎩

**Comment by kaspernissen** [comment]
This is awesome, @luxas! Great job! @jepp2078 do you have time, to handle the changes this requires in the stats-api?

**Comment by jepp2078** [comment]
After tomorrow I have some time.

**Comment by luxas** [comment]
May I merge this meanwhile? Then I can do some smaller follow-ups easily.

**Comment by AllanHoejgaardJensen** [comment]
That looks very promising @luxas - making stuff a lot simpler  :-)

**Comment by kaspernissen** [comment]
This looks good, lets just merge now and fix stats-api afterwards.

**Pull request merged**
