### PR TITLE
Add agenda for Cloud Native Bergen

### PR DESCRIPTION
**Pull request by Starefossen**
Add the Meetup agenda for for Cloud Native Bergen meetup.

### CODE REVIEW

**Comment by kaspernissen** [comment]
Thank you for adding this @Starefossen 🎉 

venues and speakers are referenced from the following files in the root; `companies.yaml` and speakers.yaml`. Could you please add the details in those files, and push it up? Thanks 🙏

**Comment by Starefossen** [comment]
Done 😄

**Comment by Steiniche** [comment]
This looks great @Starefossen!

**Comment by kaspernissen** [comment]
Thank you @Starefossen !

**Pull request merged**
