### PR TITLE
Improve generator phase5

### PR DESCRIPTION
**Pull request by luxas**
This PR fixes some outstanding issues with `config.json` as discussed with @jepp2078, @kaspernissen and @netumoliver.
This will make it easier for stats-api to read the config and generate a GraphQL-queryable database.

Changes as follows:
 - Before, speakers and companies were always marshalled as the full-blown object everywhere in config.json, although just a reference to their ID is necessary (e.g. where a presentation references a certain speaker). Now, the company/speaker IDs are marshalled instead.
 - The notion of a "Member company" has been removed completely. Instead, we now have 4 tiers of companies:
   - Longterm sponsors (those who support the meetups in a consistent fashion)
   - Meetup sponsors (bad wording, can you suggest better?) (those who have been a venue, food or similar sponsor at a meetup, or provide an organizer)
   - Speaker providers (those companies who have had a employee talk at any of our meetups)
   - Ecosystem members, not counted as "sponsors" (those who have an interest in kubernetes/cloud native, but haven't been sponsoring or speaking in any way. This is kinda our "backlog" as organizers).
 - According to these tiers, a new `sponsorTiers` map has been added to `MeetupGroup` to tell what companies have been active in that city, on what level.
 - The countries lists have been removed from speakers/companies, this can be calculated by graphql, and we'll use a city-based level instead.

@jepp2078 @kaspernissen does this look good? can we merge it to the generator refactor branch?
When done, @jepp2078 can go ahead and modify stats-api accordingly to these changes.

### CODE REVIEW

**Comment by Steiniche** [comment]
Hi @luxas thanks for the continuous effort to improve the generator!

Can you explain the sponsorTier idea in a little more detail?
I am unsure if this change adds complexity with little benefit but it is likely because I don't understand the reasons behind it.
Could you give an example from the Helsinki area as to who would be in a certain tier and why it matters?

**Comment by kaspernissen** [comment]
First of all, thanks @luxas! This looks great and follows the direction that we discussed. 
In regards to naming of the Meetup Sponsor, maybe event sponsor would be better? 

@Steiniche We want to be able to highlight what the different sponsors has helped us with.  A long-term sponsor, could be a hosting partner, or CNCF the continuously sponsor us with the meetup group and other stuff. 

Meetup/Event sponsors as @luxas mentions is sponsors at a given meetup, e.g. venue, or food.

Speaker providers should be self-explanatory

And the last one for now is the Ecosystem sponsor which is basically, right now, just a list of companies that we know are working with these projects. They will not be provided a spot on the website. 

With this, we should be able to distinguish the different sponsors on the website, sort them by their tiers etc.

@jepp2078 how does this look to you? From my perspective it looks good, but I'm not down in the nitty gritty details of the stats-api.

**Comment by jepp2078** [comment]
Looks good. I'll start aligning the stats-api now.

/lgtm

**Comment by kaspernissen** [comment]
Let's merge this into `meetup-kit-refactor` for now, then 👍

**Comment by luxas** [comment]
Thanks @jepp2078; I'll merge this PR now.

wrt the above, can you @kaspernissen and @Steiniche open a new issue to discuss the following?

**Comment by Steiniche** [comment]
Of course we can but I do not think it is needed.
From the descption @kaspernissen gave I am fine with the changes.

**Pull request merged**
