### PR TITLE
Update company for hans.duedal

### PR DESCRIPTION
**Pull request by duedal**
Switched company :)

### CODE REVIEW

**Comment by kaspernissen** [comment]
You should add yourself as an organizer of the copenhagen group as well ;)

**Comment by duedal** [comment]
Hmm, you know why it fails? Now I get 
`umeå/README.md differs from expected state`

**Comment by kaspernissen** [comment]
You should add a reference to your speaker id in the `meetups.yaml` instead of entering it in the README.md. All data in the README.md will be generated based on the `meetups.yaml` file. We should really add some documentation on how this works. 

Once you are finished editing. Could you please try to run `make pre-commit`?

**Comment by duedal** [comment]
All green now, thank you for the help @kaspernissen

**Comment by kaspernissen** [comment]
No problem, @duedal! Thank you the PR.

\lgtm

**Pull request merged**
