### PR TITLE
Add rancher slides

### PR DESCRIPTION
**Pull request by LinAnt**
Adding more, once I get them. I messaged Sachin.

### CODE REVIEW

**Comment by kaspernissen** [comment]
@LinAnt we prefer online slides. We have some issues with GitLFS, if there's a way to share slides via google slide, speakerdeck, etc. and just reference these from the agenda, it would be great :)

**Comment by LinAnt** [comment]
👍 Getting a world viewable link instead :)

**Comment by luxas** [comment]
@LinAnt please also add my slides when you're at it:

- https://speakerdeck.com/luxas/kubernetes-and-cncf-meetup-helsinki-october-2019
- https://speakerdeck.com/luxas/kubernetes-finland-workshop-october-2019
- https://speakerdeck.com/luxas/kubernetes-and-cncf-meetup-turku-october-2019
- https://speakerdeck.com/luxas/intro-to-the-cloud-native-world-of-kubernetes-october-2019

**Comment by LinAnt** [comment]
Did a forcepush to get rid of the static file I uploaded earlier :)

**Pull request merged**
