### PR TITLE
Add YAML to README generator

### PR DESCRIPTION
**Pull request by luxas**
Fixes: #3 
@kaspernissen @netumoliver

### CODE REVIEW

**Comment by Steiniche** [comment]
Looks great @luxas!
One question: Should meetups.yaml be ignored as well or then the current one could be an example instead?

**Comment by luxas** [comment]
Now everything is gonna be genersted from meetups.yaml eventually

**Comment by netumoliver** [comment]
Looks very good to me as well.
Did you have in mind to have one yaml per country or all in one?

**Comment by luxas** [comment]
I'd like to have speakers and companies in the same centralized list, but meetup groups can have their own filw eventually as a follow up indeed

**Comment by kaspernissen** [comment]
Great work @luxas ! It makes sense to have speakers and companies in a centralized list, but I think we should have a `meetups.yaml` for each meetup group, otherwise the file will probably get very bloated.

**Comment by kaspernissen** [comment]
I was just wondering, would it make sense to have a separate repo for the generator, and let this repo contain the generated markdown and of course presentations etc. as we have them now?

**Comment by luxas** [comment]
> I think we should have a `meetups.yaml` for each meetup group, otherwise the file will probably get very bloated.

Yep, that makes sense to me. This is just the initial code needed. You can PR that :wink:

> would it make sense to have a separate repo for the generator, and let this repo contain the generated markdown and of course presentations etc. as we have them now?

I don't think so. It's a very small go program, I'm planning to do CI with the generator, so we'd have pre-merge checks of that the generated code is correct, and then it's way easier to have it centralized. I don't think it bloats this repo to a large extent.

**Pull request merged**
